remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: [STICKnoLOGIC CDN]
tagline: [A curated JavaScript ans CSS]
description: [A curated collection of CSS and JavaScript libraries, hosted on GitHub Pages and served via CDN.Perfect for developers who want reliable, lightweight, and easy-to-use frontend assets.]